use rusqlite::{params, Connection};

/// 种子命令数据（含 H3C/华为/思科/锐捷/飞塔/Linux 常用巡检命令）
///
/// 使用 `INSERT OR IGNORE` 幂等插入：依赖 `command_pool` 的 `UNIQUE(vendor, command)` 约束，
/// 已存在的命令会被忽略，新增的种子命令会自动补充。每次启动都会执行，确保种子数据完整。
/// 返回实际新插入的行数。
pub fn seed_command_pool(conn: &mut Connection) -> Result<usize, String> {
    let commands: Vec<(&str, &str, &str, &str, i64)> = vec![
        // ==================== H3C (Comware V5/V7，已真机验证) ====================
        ("H3C", "display clock", "查看系统时钟", "clock", 0),
        ("H3C", "display ntp status", "查看 NTP 状态", "clock", 0),
        ("H3C", "display cpu-usage summary", "查看 CPU 利用率", "cpu", 0),
        ("H3C", "display environment", "查看环境状态", "env", 0),
        ("H3C", "display fan", "查看风扇状态", "fan", 0),
        ("H3C", "display current-configuration | include sysname", "主机名", "general", 0),
        ("H3C", "dir", "Flash空间使用情况", "hardware", 0),
        ("H3C", "display device", "查看设备信息", "hardware", 0),
        ("H3C", "display device manuinfo", "查看设备序列号", "hardware", 0),
        ("H3C", "display irf", "查看 IRF 状态", "hardware", 0),
        ("H3C", "display transceiver", "查看光模块信息", "hardware", 0),
        ("H3C", "display interface", "查看接口详细信息", "interface", 0),
        ("H3C", "display interface brief", "查看接口概要", "interface", 0),
        ("H3C", "display logbuffer last-mins 5", "查看日志摘要", "log", 0),
        ("H3C", "display memory summary", "查看内存利用率", "memory", 0),
        ("H3C", "display power", "查看电源状态", "power", 0),
        ("H3C", "display arp", "查看 ARP 表", "protocol", 0),
        ("H3C", "display ip routing-table", "查看路由表", "protocol", 0),
        ("H3C", "display stp brief", "生成树状态", "protocol", 0),
        ("H3C", "display version", "查看系统版本", "version", 0),
        ("H3C", "display mac-address", "查看 MAC 地址表", "vlan", 0),
        ("H3C", "display vlan", "查看 VLAN 信息", "vlan", 0),
        ("H3C", "display wlan ap all", "检查 AP 整体上线状态", "wireless", 0),
        ("H3C", "display wlan service-template", "无线服务模板（SSID）状态", "wireless", 0),
        // ==================== 华为 (Huawei VRP) ====================
        ("华为", "display clock", "查看系统时钟", "clock", 0),
        ("华为", "display ntp-status", "查看 NTP 状态", "clock", 0),
        ("华为", "display cpu-usage", "查看 CPU 利用率", "cpu", 0),
        ("华为", "display environment", "查看环境状态", "env", 0),
        ("华为", "display temperature all", "查看所有温度传感器", "env", 0),
        ("华为", "display fan", "查看风扇状态", "fan", 0),
        ("华为", "display current-configuration | include sysname", "主机名", "general", 0),
        ("华为", "display device", "查看设备信息", "hardware", 0),
        ("华为", "display elabel", "查看设备序列号/电子标签", "hardware", 0),
        ("华为", "display health", "查看设备健康状态", "hardware", 0),
        ("华为", "display stack", "查看堆叠状态", "hardware", 0),
        ("华为", "display transceiver", "查看光模块信息", "hardware", 0),
        ("华为", "display interface", "查看接口详细信息", "interface", 0),
        ("华为", "display interface brief", "查看接口概要", "interface", 0),
        ("华为", "display ip interface brief", "查看 IP 接口概要", "interface", 0),
        ("华为", "display logbuffer", "查看日志摘要", "log", 0),
        ("华为", "display memory-usage", "查看内存利用率", "memory", 0),
        ("华为", "display power", "查看电源状态", "power", 0),
        ("华为", "display arp", "查看 ARP 表", "protocol", 0),
        ("华为", "display ip routing-table", "查看路由表", "protocol", 0),
        ("华为", "display stp brief", "生成树状态", "protocol", 0),
        ("华为", "display version", "查看系统版本", "version", 0),
        ("华为", "display mac-address", "查看 MAC 地址表", "vlan", 0),
        ("华为", "display vlan", "查看 VLAN 信息", "vlan", 0),
        // ==================== 思科 (Cisco IOS) ====================
        ("思科", "show clock", "查看系统时钟", "clock", 0),
        ("思科", "show ntp associations", "查看 NTP 状态", "clock", 0),
        ("思科", "show processes cpu", "查看 CPU 利用率", "cpu", 0),
        ("思科", "show processes cpu history", "查看 CPU 历史使用", "cpu", 0),
        ("思科", "show environment", "查看环境状态", "env", 0),
        ("思科", "show running-config", "查看运行配置", "general", 0),
        ("思科", "show running-config | include hostname", "主机名", "general", 0),
        ("思科", "show version | include uptime", "查看运行时间", "general", 0),
        ("思科", "show inventory", "查看设备信息", "hardware", 0),
        ("思科", "show interface summary", "查看接口摘要", "interface", 0),
        ("思科", "show interfaces status", "查看接口状态", "interface", 0),
        ("思科", "show interfaces trunk", "查看 Trunk", "interface", 0),
        ("思科", "show ip interface brief", "查看 IP 接口概要", "interface", 0),
        ("思科", "show logging", "查看日志", "log", 0),
        ("思科", "show memory statistics", "查看内存利用率", "memory", 0),
        ("思科", "show power", "查看电源状态", "power", 0),
        ("思科", "show arp", "查看 ARP 表", "protocol", 0),
        ("思科", "show cdp neighbors", "查看 CDP 邻居", "protocol", 0),
        ("思科", "show ip route", "查看路由表", "protocol", 0),
        ("思科", "show spanning-tree", "生成树状态", "protocol", 0),
        ("思科", "show version", "查看系统版本", "version", 0),
        ("思科", "show mac address-table", "查看 MAC 地址表", "vlan", 0),
        ("思科", "show vlan brief", "查看 VLAN 信息", "vlan", 0),
        // ==================== 锐捷 (Ruijie RGOS) ====================
        ("锐捷", "show clock", "查看系统时钟", "clock", 0),
        ("锐捷", "show ntp", "查看 NTP 状态", "clock", 0),
        ("锐捷", "show cpu", "查看 CPU 利用率", "cpu", 0),
        ("锐捷", "show environment", "查看环境状态", "env", 0),
        ("锐捷", "show temperature", "查看设备温度", "env", 0),
        ("锐捷", "show running-config | include hostname", "主机名", "general", 0),
        ("锐捷", "show inventory", "查看设备信息/序列号", "hardware", 0),
        ("锐捷", "show transceiver", "查看光模块信息", "hardware", 0),
        ("锐捷", "show interface", "查看接口详细信息", "interface", 0),
        ("锐捷", "show interface brief", "查看接口概要", "interface", 0),
        ("锐捷", "show interfaces status", "查看接口状态", "interface", 0),
        ("锐捷", "show logging", "查看日志", "log", 0),
        ("锐捷", "show memory", "查看内存利用率", "memory", 0),
        ("锐捷", "show power", "查看电源状态", "power", 0),
        ("锐捷", "show arp", "查看 ARP 表", "protocol", 0),
        ("锐捷", "show dhcp snooping", "查看 DHCP Snooping", "protocol", 0),
        ("锐捷", "show ip route", "查看路由表", "protocol", 0),
        ("锐捷", "show spanning-tree", "生成树状态", "protocol", 0),
        ("锐捷", "show version", "查看系统版本", "version", 0),
        ("锐捷", "show mac-address-table", "查看 MAC 地址表", "vlan", 0),
        ("锐捷", "show vlan", "查看 VLAN 信息", "vlan", 0),
        // ==================== 飞塔 (Fortinet FortiGate) ====================
        ("飞塔", "get system status", "系统状态/主机名/型号/序列号", "version", 0),
        ("飞塔", "get system performance status", "查看性能状态", "cpu", 0),
        ("飞塔", "diagnose sys top-summary", "查看进程与资源摘要", "cpu", 0),
        ("飞塔", "get hardware status", "查看硬件状态", "hardware", 0),
        ("飞塔", "diagnose hardware sysinfo memory", "查看内存信息", "memory", 0),
        ("飞塔", "diagnose hardware sysinfo shm", "查看共享内存信息", "memory", 0),
        ("飞塔", "get system interface physical", "查看物理接口", "interface", 0),
        ("飞塔", "diagnose hardware deviceinfo nic", "查看网卡硬件信息", "interface", 0),
        ("飞塔", "get router info routing-table all", "查看路由表", "protocol", 0),
        ("飞塔", "diagnose ip arp list", "查看 ARP 表", "protocol", 0),
        ("飞塔", "diagnose sys session stat", "查看会话统计", "protocol", 0),
        ("飞塔", "get firewall policy", "查看防火墙策略", "security", 0),
        ("飞塔", "diagnose firewall iprope show", "查看策略匹配结构", "security", 0),
        ("飞塔", "get vpn ipsec tunnel summary", "查看 IPsec VPN 摘要", "vpn", 0),
        ("飞塔", "diagnose vpn tunnel list", "查看 VPN 隧道详情", "vpn", 0),
        ("飞塔", "get system ha status", "查看 HA 状态", "ha", 0),
        ("飞塔", "execute log display", "查看系统日志", "log", 0),
        ("飞塔", "diagnose debug crashlog read", "查看崩溃日志", "log", 0),
        // ==================== Linux ====================
        // 系统信息
        ("Linux", "hostnamectl", "主机名和系统信息", "system", 0),
        ("Linux", "uname -a", "内核版本", "system", 0),
        ("Linux", "cat /etc/os-release", "发行版信息", "system", 0),
        ("Linux", "uptime", "运行时间和负载", "system", 0),
        ("Linux", "timedatectl", "时区和时间同步", "system", 0),
        // CPU
        ("Linux", "lscpu", "CPU 架构信息", "cpu", 0),
        ("Linux", "cat /proc/cpuinfo", "CPU 详细信息", "cpu", 0),
        ("Linux", "top -bn1 | head -20", "CPU 使用率快照", "cpu", 0),
        // 内存
        ("Linux", "free -h", "内存使用概况", "memory", 0),
        ("Linux", "cat /proc/meminfo", "内存详细信息", "memory", 0),
        // 磁盘
        ("Linux", "df -h", "磁盘使用率", "disk", 0),
        ("Linux", "lsblk", "块设备列表", "disk", 0),
        ("Linux", "iostat -x 1 1", "磁盘 I/O 统计", "disk", 0),
        ("Linux", "fdisk -l", "磁盘分区详情", "disk", 1),
        // 网络
        ("Linux", "ip addr", "网络接口和 IP", "network", 0),
        ("Linux", "ip route", "路由表", "network", 0),
        ("Linux", "ss -tlnp", "监听端口", "network", 0),
        ("Linux", "ss -s", "连接统计", "network", 0),
        ("Linux", "cat /etc/resolv.conf", "DNS 配置", "network", 0),
        // 服务
        ("Linux", "systemctl list-units --type=service --state=running --no-pager", "运行中的服务", "service", 0),
        ("Linux", "systemctl list-units --state=failed --no-pager", "失败的服务", "service", 0),
        // 进程
        ("Linux", "ps aux --sort=-%cpu | head -15", "CPU 占用 Top 进程", "process", 0),
        ("Linux", "ps aux --sort=-%mem | head -15", "内存占用 Top 进程", "process", 0),
        // 日志
        ("Linux", "journalctl -p err --no-pager -n 30", "最近错误日志", "log", 0),
        ("Linux", "dmesg | tail -30", "内核日志", "log", 0),
        ("Linux", "cat /var/log/syslog | tail -30", "系统日志", "log", 1),
        // 安全
        ("Linux", "last -10", "最近登录记录", "security", 0),
        ("Linux", "lastlog | grep -v Never", "所有用户最后登录", "security", 0),
        ("Linux", "cat /etc/passwd | grep -v nologin | grep -v false", "可登录用户", "security", 0),
        ("Linux", "iptables -L -n", "防火墙规则", "security", 1),
        // 硬件/内核
        ("Linux", "dmidecode -t system", "系统硬件信息", "hardware", 1),
        ("Linux", "lspci", "PCI 设备列表", "hardware", 0),
        ("Linux", "cat /proc/loadavg", "负载均值", "hardware", 0),
        ("Linux", "sysctl -a 2>/dev/null | head -30", "内核参数", "hardware", 0),
        // 定时任务
        ("Linux", "crontab -l", "当前用户定时任务", "schedule", 0),
        ("Linux", "systemctl list-timers --no-pager", "systemd 定时器", "schedule", 0),
        // ==================== Ubuntu (通用 + 发行版特有) ====================
        // --- 通用命令 ---
        ("Ubuntu", "hostnamectl", "主机名和系统信息", "system", 0),
        ("Ubuntu", "uname -a", "内核版本", "system", 0),
        ("Ubuntu", "cat /etc/os-release", "发行版信息", "system", 0),
        ("Ubuntu", "uptime", "运行时间和负载", "system", 0),
        ("Ubuntu", "timedatectl", "时区和时间同步", "system", 0),
        ("Ubuntu", "lscpu", "CPU 架构信息", "cpu", 0),
        ("Ubuntu", "cat /proc/cpuinfo", "CPU 详细信息", "cpu", 0),
        ("Ubuntu", "top -bn1 | head -20", "CPU 使用率快照", "cpu", 0),
        ("Ubuntu", "free -h", "内存使用概况", "memory", 0),
        ("Ubuntu", "cat /proc/meminfo", "内存详细信息", "memory", 0),
        ("Ubuntu", "df -h", "磁盘使用率", "disk", 0),
        ("Ubuntu", "lsblk", "块设备列表", "disk", 0),
        ("Ubuntu", "iostat -x 1 1", "磁盘 I/O 统计", "disk", 0),
        ("Ubuntu", "fdisk -l", "磁盘分区详情", "disk", 1),
        ("Ubuntu", "ip addr", "网络接口和 IP", "network", 0),
        ("Ubuntu", "ip route", "路由表", "network", 0),
        ("Ubuntu", "ss -tlnp", "监听端口", "network", 0),
        ("Ubuntu", "ss -s", "连接统计", "network", 0),
        ("Ubuntu", "cat /etc/resolv.conf", "DNS 配置", "network", 0),
        ("Ubuntu", "systemctl list-units --type=service --state=running --no-pager", "运行中的服务", "service", 0),
        ("Ubuntu", "systemctl list-units --state=failed --no-pager", "失败的服务", "service", 0),
        ("Ubuntu", "ps aux --sort=-%cpu | head -15", "CPU 占用 Top 进程", "process", 0),
        ("Ubuntu", "ps aux --sort=-%mem | head -15", "内存占用 Top 进程", "process", 0),
        ("Ubuntu", "journalctl -p err --no-pager -n 30", "最近错误日志", "log", 0),
        ("Ubuntu", "dmesg | tail -30", "内核日志", "log", 0),
        ("Ubuntu", "cat /var/log/syslog | tail -30", "系统日志", "log", 1),
        ("Ubuntu", "last -10", "最近登录记录", "security", 0),
        ("Ubuntu", "lastlog | grep -v Never", "所有用户最后登录", "security", 0),
        ("Ubuntu", "cat /etc/passwd | grep -v nologin | grep -v false", "可登录用户", "security", 0),
        ("Ubuntu", "iptables -L -n", "防火墙规则", "security", 1),
        ("Ubuntu", "dmidecode -t system", "系统硬件信息", "hardware", 1),
        ("Ubuntu", "lspci", "PCI 设备列表", "hardware", 0),
        ("Ubuntu", "cat /proc/loadavg", "负载均值", "hardware", 0),
        ("Ubuntu", "sysctl -a 2>/dev/null | head -30", "内核参数", "hardware", 0),
        ("Ubuntu", "crontab -l", "当前用户定时任务", "schedule", 0),
        ("Ubuntu", "systemctl list-timers --no-pager", "systemd 定时器", "schedule", 0),
        // --- 发行版特有命令 ---
        ("Ubuntu", "apt list --installed 2>/dev/null | head -20", "已安装软件包", "system", 0),
        ("Ubuntu", "cat /etc/apt/sources.list", "APT 源配置", "system", 0),
        ("Ubuntu", "snap list 2>/dev/null", "Snap 包列表", "system", 0),
        // ==================== CentOS (通用 + 发行版特有) ====================
        // --- 通用命令 ---
        ("CentOS", "hostnamectl", "主机名和系统信息", "system", 0),
        ("CentOS", "uname -a", "内核版本", "system", 0),
        ("CentOS", "cat /etc/os-release", "发行版信息", "system", 0),
        ("CentOS", "uptime", "运行时间和负载", "system", 0),
        ("CentOS", "timedatectl", "时区和时间同步", "system", 0),
        ("CentOS", "lscpu", "CPU 架构信息", "cpu", 0),
        ("CentOS", "cat /proc/cpuinfo", "CPU 详细信息", "cpu", 0),
        ("CentOS", "top -bn1 | head -20", "CPU 使用率快照", "cpu", 0),
        ("CentOS", "free -h", "内存使用概况", "memory", 0),
        ("CentOS", "cat /proc/meminfo", "内存详细信息", "memory", 0),
        ("CentOS", "df -h", "磁盘使用率", "disk", 0),
        ("CentOS", "lsblk", "块设备列表", "disk", 0),
        ("CentOS", "iostat -x 1 1", "磁盘 I/O 统计", "disk", 0),
        ("CentOS", "fdisk -l", "磁盘分区详情", "disk", 1),
        ("CentOS", "ip addr", "网络接口和 IP", "network", 0),
        ("CentOS", "ip route", "路由表", "network", 0),
        ("CentOS", "ss -tlnp", "监听端口", "network", 0),
        ("CentOS", "ss -s", "连接统计", "network", 0),
        ("CentOS", "cat /etc/resolv.conf", "DNS 配置", "network", 0),
        ("CentOS", "systemctl list-units --type=service --state=running --no-pager", "运行中的服务", "service", 0),
        ("CentOS", "systemctl list-units --state=failed --no-pager", "失败的服务", "service", 0),
        ("CentOS", "ps aux --sort=-%cpu | head -15", "CPU 占用 Top 进程", "process", 0),
        ("CentOS", "ps aux --sort=-%mem | head -15", "内存占用 Top 进程", "process", 0),
        ("CentOS", "journalctl -p err --no-pager -n 30", "最近错误日志", "log", 0),
        ("CentOS", "dmesg | tail -30", "内核日志", "log", 0),
        ("CentOS", "cat /var/log/syslog | tail -30", "系统日志", "log", 1),
        ("CentOS", "last -10", "最近登录记录", "security", 0),
        ("CentOS", "lastlog | grep -v Never", "所有用户最后登录", "security", 0),
        ("CentOS", "cat /etc/passwd | grep -v nologin | grep -v false", "可登录用户", "security", 0),
        ("CentOS", "iptables -L -n", "防火墙规则", "security", 1),
        ("CentOS", "dmidecode -t system", "系统硬件信息", "hardware", 1),
        ("CentOS", "lspci", "PCI 设备列表", "hardware", 0),
        ("CentOS", "cat /proc/loadavg", "负载均值", "hardware", 0),
        ("CentOS", "sysctl -a 2>/dev/null | head -30", "内核参数", "hardware", 0),
        ("CentOS", "crontab -l", "当前用户定时任务", "schedule", 0),
        ("CentOS", "systemctl list-timers --no-pager", "systemd 定时器", "schedule", 0),
        // --- 发行版特有命令 ---
        ("CentOS", "cat /etc/centos-release", "CentOS 版本", "system", 0),
        ("CentOS", "rpm -qa | head -20", "已安装 RPM 包", "system", 0),
        ("CentOS", "yum repolist 2>/dev/null", "YUM 源配置", "system", 0),
        // ==================== Rocky (通用 + 发行版特有) ====================
        // --- 通用命令 ---
        ("Rocky", "hostnamectl", "主机名和系统信息", "system", 0),
        ("Rocky", "uname -a", "内核版本", "system", 0),
        ("Rocky", "cat /etc/os-release", "发行版信息", "system", 0),
        ("Rocky", "uptime", "运行时间和负载", "system", 0),
        ("Rocky", "timedatectl", "时区和时间同步", "system", 0),
        ("Rocky", "lscpu", "CPU 架构信息", "cpu", 0),
        ("Rocky", "cat /proc/cpuinfo", "CPU 详细信息", "cpu", 0),
        ("Rocky", "top -bn1 | head -20", "CPU 使用率快照", "cpu", 0),
        ("Rocky", "free -h", "内存使用概况", "memory", 0),
        ("Rocky", "cat /proc/meminfo", "内存详细信息", "memory", 0),
        ("Rocky", "df -h", "磁盘使用率", "disk", 0),
        ("Rocky", "lsblk", "块设备列表", "disk", 0),
        ("Rocky", "iostat -x 1 1", "磁盘 I/O 统计", "disk", 0),
        ("Rocky", "fdisk -l", "磁盘分区详情", "disk", 1),
        ("Rocky", "ip addr", "网络接口和 IP", "network", 0),
        ("Rocky", "ip route", "路由表", "network", 0),
        ("Rocky", "ss -tlnp", "监听端口", "network", 0),
        ("Rocky", "ss -s", "连接统计", "network", 0),
        ("Rocky", "cat /etc/resolv.conf", "DNS 配置", "network", 0),
        ("Rocky", "systemctl list-units --type=service --state=running --no-pager", "运行中的服务", "service", 0),
        ("Rocky", "systemctl list-units --state=failed --no-pager", "失败的服务", "service", 0),
        ("Rocky", "ps aux --sort=-%cpu | head -15", "CPU 占用 Top 进程", "process", 0),
        ("Rocky", "ps aux --sort=-%mem | head -15", "内存占用 Top 进程", "process", 0),
        ("Rocky", "journalctl -p err --no-pager -n 30", "最近错误日志", "log", 0),
        ("Rocky", "dmesg | tail -30", "内核日志", "log", 0),
        ("Rocky", "cat /var/log/syslog | tail -30", "系统日志", "log", 1),
        ("Rocky", "last -10", "最近登录记录", "security", 0),
        ("Rocky", "lastlog | grep -v Never", "所有用户最后登录", "security", 0),
        ("Rocky", "cat /etc/passwd | grep -v nologin | grep -v false", "可登录用户", "security", 0),
        ("Rocky", "iptables -L -n", "防火墙规则", "security", 1),
        ("Rocky", "dmidecode -t system", "系统硬件信息", "hardware", 1),
        ("Rocky", "lspci", "PCI 设备列表", "hardware", 0),
        ("Rocky", "cat /proc/loadavg", "负载均值", "hardware", 0),
        ("Rocky", "sysctl -a 2>/dev/null | head -30", "内核参数", "hardware", 0),
        ("Rocky", "crontab -l", "当前用户定时任务", "schedule", 0),
        ("Rocky", "systemctl list-timers --no-pager", "systemd 定时器", "schedule", 0),
        // --- 发行版特有命令 ---
        ("Rocky", "cat /etc/rocky-release", "Rocky 版本", "system", 0),
        ("Rocky", "rpm -qa | head -20", "已安装 RPM 包", "system", 0),
        ("Rocky", "dnf repolist 2>/dev/null", "DNF 源配置", "system", 0),
        // ==================== Debian (通用 + 发行版特有) ====================
        // --- 通用命令 ---
        ("Debian", "hostnamectl", "主机名和系统信息", "system", 0),
        ("Debian", "uname -a", "内核版本", "system", 0),
        ("Debian", "cat /etc/os-release", "发行版信息", "system", 0),
        ("Debian", "uptime", "运行时间和负载", "system", 0),
        ("Debian", "timedatectl", "时区和时间同步", "system", 0),
        ("Debian", "lscpu", "CPU 架构信息", "cpu", 0),
        ("Debian", "cat /proc/cpuinfo", "CPU 详细信息", "cpu", 0),
        ("Debian", "top -bn1 | head -20", "CPU 使用率快照", "cpu", 0),
        ("Debian", "free -h", "内存使用概况", "memory", 0),
        ("Debian", "cat /proc/meminfo", "内存详细信息", "memory", 0),
        ("Debian", "df -h", "磁盘使用率", "disk", 0),
        ("Debian", "lsblk", "块设备列表", "disk", 0),
        ("Debian", "iostat -x 1 1", "磁盘 I/O 统计", "disk", 0),
        ("Debian", "fdisk -l", "磁盘分区详情", "disk", 1),
        ("Debian", "ip addr", "网络接口和 IP", "network", 0),
        ("Debian", "ip route", "路由表", "network", 0),
        ("Debian", "ss -tlnp", "监听端口", "network", 0),
        ("Debian", "ss -s", "连接统计", "network", 0),
        ("Debian", "cat /etc/resolv.conf", "DNS 配置", "network", 0),
        ("Debian", "systemctl list-units --type=service --state=running --no-pager", "运行中的服务", "service", 0),
        ("Debian", "systemctl list-units --state=failed --no-pager", "失败的服务", "service", 0),
        ("Debian", "ps aux --sort=-%cpu | head -15", "CPU 占用 Top 进程", "process", 0),
        ("Debian", "ps aux --sort=-%mem | head -15", "内存占用 Top 进程", "process", 0),
        ("Debian", "journalctl -p err --no-pager -n 30", "最近错误日志", "log", 0),
        ("Debian", "dmesg | tail -30", "内核日志", "log", 0),
        ("Debian", "cat /var/log/syslog | tail -30", "系统日志", "log", 1),
        ("Debian", "last -10", "最近登录记录", "security", 0),
        ("Debian", "lastlog | grep -v Never", "所有用户最后登录", "security", 0),
        ("Debian", "cat /etc/passwd | grep -v nologin | grep -v false", "可登录用户", "security", 0),
        ("Debian", "iptables -L -n", "防火墙规则", "security", 1),
        ("Debian", "dmidecode -t system", "系统硬件信息", "hardware", 1),
        ("Debian", "lspci", "PCI 设备列表", "hardware", 0),
        ("Debian", "cat /proc/loadavg", "负载均值", "hardware", 0),
        ("Debian", "sysctl -a 2>/dev/null | head -30", "内核参数", "hardware", 0),
        ("Debian", "crontab -l", "当前用户定时任务", "schedule", 0),
        ("Debian", "systemctl list-timers --no-pager", "systemd 定时器", "schedule", 0),
        // --- 发行版特有命令 ---
        ("Debian", "cat /etc/debian_version", "Debian 版本", "system", 0),
        ("Debian", "dpkg -l | head -20", "已安装 DEB 包", "system", 0),
        ("Debian", "cat /etc/apt/sources.list", "APT 源配置", "system", 0),
    ];

    let tx = conn.transaction().map_err(|e| e.to_string())?;
    let inserted = {
        let mut stmt = tx
            .prepare("INSERT OR IGNORE INTO command_pool (vendor, command, description, category, needs_root) VALUES (?1, ?2, ?3, ?4, ?5)")
            .map_err(|e| e.to_string())?;
        let mut inserted = 0usize;
        for (vendor, command, description, category, needs_root) in &commands {
            let rows = stmt
                .execute(params![vendor, command, description, category, needs_root])
                .map_err(|e| format!("插入种子命令失败 ({}): {}", command, e))?;
            inserted += rows;
        }
        inserted
    };
    tx.commit().map_err(|e| e.to_string())?;
    Ok(inserted)
}
